data:
  original_data: ${data.export_template}
  target_data: ${data.evaluation.target_data}
  template_file:  ${general.run_dir}/template/outputs/template_sample.h5
  original_SB1_data: ${data.export_SB1}
  original_SB2_data: ${data.export_SB2}
  SB1_gen_file: ${general.run_dir}/template/outputs/SB1_gen_sample.h5
  SB2_gen_file: ${general.run_dir}/template/outputs/SB1_gen_sample.h5

x_bounds: [null, null]
debug_eval: False
get_best: False

procedures: null