data:
  original_data: ${data.export_template}
  target_data: ${data.export_template}
  template_file:  ${general.run_dir}/template/outputs/template_sample.h5
  original_SB1_data: ${data.export_SB1}
  original_SB2_data: ${data.export_SB2}
  SB1_gen_file: ${general.run_dir}/template/outputs/SB1_gen_sample.h5
  SB2_gen_file: ${general.run_dir}/template/outputs/SB1_gen_sample.h5

x_bounds: [null, null]
debug_eval: False
get_best: False
do_2d_hist_instead_of_contour: True

plot_contour_SB1toSB2transport: True
plot_classifier_SB1toSB2transport: True
plot_everything_else: False

procedures: null