seed: ${general.seed} 
data: ${data.export_SB1toSR} 

paths:
  # output dir will be created by hydra
  full_path:  ${general.run_dir}/template
  output_dir:  ${general.run_dir}/template

output_name: SB1toSR_gen_sample

get_best: false
network_name: ${step_train_template.network_name}