full_run_cfg: null
run_dir: null
# Change the seed for the template training
several_template_train_seeds: [1, 2, 3, 4, 5] 

# Change the number of signal events doped 
several_doping: [0]
check_doping: 3000 #a value from the original config file to replace
redo: False
run_sequentially: False # Run the experiments sequentially
do_stability_analysis: True
do_metric_aggregation: True
not_just_seeds: True
overrides: ["step_cwola=BDT_LHCO_oversampling_experiment", "step_evaluate=transit_LHCO", "step_cwola=BDT_LHCO_allCWOLA_SBcheck", "do_collect_metrics=1"]
one_run_sh: /home/users/o/oleksiyu/WORK/hyperproject/transit/jobs/PAPER/TRANSITv0v2_LHCO_one_run_hyper1h.sh
hyperparameters:
  g_loss_gen_weight: 0.2
  w_cons: 0.1
  latent_dim: 8
  num_blocks: 3
  hddn_dim: 128
  disc_hidd: 64

stability_analysis_cfg:
  run_dir: null
  save_curves: True
  postfix: "comb_seeds_CWOLA"

  main_methods:
    transit: 
      rel_directory: "/"
      prefix: "transit_"
      postfix: "_comb_CWOLA"
    transitLatent: 
      rel_directory : "/"
      prefix: "transitLatent_"
      postfix: "_comb_CWOLA"


  methods: #"CURTAINS": "/home/users/o/oleksiyu/WORK/hyperproject/lit/curtains/run_7",
    supervised: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/supervised"
      prefix: ""
      postfix: ""
    idealised: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/idealised"
      prefix: ""
      postfix: ""
    radot: 
      abs_directory: "/home/users/o/oleksiyu/WORK/hyperproject/lit/radot/dope_3000/standard"
      prefix: ""
      postfix: ""