# @package _global_

defaults:
  - _self_
  - private: private_baobab
  - path: user
  - data: SKY_DEFAULT
  - step_train_template: transit_reco_adv
  - step_export_template: transit
  - step_export_SB1: default
  - step_export_SB2: default
  - step_evaluate: transit_SKY
  - experiment/TRANSITv25f_std_SKY@_global_
  - override step_train_template/trainer: 5e_noclip.yaml


step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

delete_existing_run_dir: True

do_train_template: True
do_export_template: True
do_transport_sideband: True
do_export_latent: False
do_evaluation: True
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False


verbose_validation: True

general:
  name: TRANSITv25f_std_SKY_debug
  subfolder: TEST_SKY_2502/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False
