# @package _global_

defaults:
  - _self_
  - data: PAD_DEFAULT
  - step_train_template: transitv_0v2
  - step_export_template: transit
  - step_evaluate: transit_PAD
  - override /step_train_template/model: TRANSITv25f_std.yaml
  #- override /step_train_template/trainer: 1e_noclip.yaml

step_train_template:
  model:
    reverse_pass_mode: additional_input
  do_scale_epochs: True
  trainer:
    check_val_every_n_epoch: 1
  preprocessing_pkl: ${general.run_dir}/../data/data/preprocessor.pkl

delete_existing_run_dir: False

do_train_template: True
do_export_template: True
do_transport_sideband: False
do_export_latent: False
do_evaluation: False
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

verbose_validation: False

general:
  name: TRANSITpad_v25fstd
  seed: 12345 # For reproducibility
  run_dir: /transit #workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False
  
