# @package _global_

defaults:
  - _self_
  - private: private_baobab
  - path: user
  - data: SKY_DEFAULT
  - step_train_template: transitv_0v2
  - step_export_template: transit
  - step_export_SB1: default
  - step_export_SB2: default
  - step_export_SB1toSR: default
  - step_export_SB2toSR: default
  - step_evaluate: transit_SKY
  - experiment/TRANSITv25f_std_SKY@_global_

step_train_template:
  wandb_key: ${private.wandb_key}
  batches_per_epoch_desired: 200

delete_existing_run_dir: False

do_train_template: True
do_export_template: True
do_transport_sideband: True
do_export_latent: False
do_evaluation: True
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

verbose_validation: False

general:
  name: TRANSITsky_vSKYv1v2
  subfolder: TEST_SKY_0603/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False

# Configs that are duplicated in a different location just to make sure that retrieve_details in cwola step of the SKY pipeline works
datamodule: ${data.template_training}
save_config_to_parent: True
