# @package _global_

defaults:
  - _self_
  - private: private_baobab
  - path: user
  - data: SKY_DEFAULT
  - step_train_template: transitv_0v2
  - step_export_template: transit
  - step_export_SB1: default
  - step_export_SB2: default
  - step_export_SB1toSR: default
  - step_export_SB2toSR: default
  - step_evaluate: transit_SKY
  - override /step_train_template/model: TRANSIT_vSKYv1v5_std.yaml

step_train_template:
  model:
    input_type: sky_train
  trainer:
    check_val_every_n_epoch: 1
  do_scale_epochs: True
  wandb_key: ${private.wandb_key}

delete_existing_run_dir: False

do_train_template: True
do_export_template: True
do_transport_sideband: True
do_export_latent: False
do_evaluation: True
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False

verbose_validation: False

general:
  name: TRANSITsky_vSKYv1v4
  subfolder: TEST_SKY_0603/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False
  
