# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_DEFAULT_speed
  - step_train_template: transitv_0v2
  - step_export_template: transit_LHCO
  - step_export_SB1: default
  - step_export_SB2: default
  - step_evaluate: transit_LHCO_fast
  - step_cwola: BDT_LHCO_SBcheck
  - step_export_latent: default
  - step_plot_compare: transit_LHCO
  - step_collect_metrics: default

hyperparameters:
  g_loss_gen_weight: 0.2
  w_cons: 0.1
  latent_dim: 8
  num_blocks: 3
  hddn_dim: 128
  disc_hidd: 64

delete_existing_run_dir: False

do_train_template: True
do_export_template: True
do_export_latent: True
do_transport_sideband: True
do_evaluation: False
do_cwola: True
do_evaluate_cwola: True
do_plot_compare: True
do_collect_metrics: True

verbose_validation: False
do_update_runtime_file: True

general:
  name: TRANSITv0v2_LHCO
  subfolder: TEST/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: True
