# @package _global_

defaults:
  - _self_
  - private: private_baobab
  - path: user
  - data: SKY_DEFAULT
  - step_train_template: transitv_0v2
  - step_export_template: transit
  - step_export_SB1: default
  - step_export_SB2: default
  - step_evaluate: transit_SKY
  - experiment/TRANSITv25f_std_SKY@_global_

step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

delete_existing_run_dir: False

do_train_template: True
do_export_template: True
do_transport_sideband: True
do_export_latent: False
do_evaluation: True
do_cwola: False
do_evaluate_cwola: False
do_plot_compare: False


verbose_validation: True

general:
  name: TRANSITsky_v25fstd
  subfolder: TEST_SKY_0603/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False
