# @package _global_

defaults:
  - _self_
  - path: user
  - data: LHCO_DEFAULT
  - step_train_template: transit_reco_adv
  - step_export_template: transit_LHCO
  - step_export_SB1: default
  - step_export_SB2: default
  - step_evaluate: transit_LHCO_fast
  - step_cwola: BDT_LHCO_allCWOLA
  - step_export_latent: default
  - step_plot_compare: transit_LHCO
  - experiment/TRANSITv0v1_LHCO_test@_global_

step_train_template:
  model:
    reverse_pass_mode: additional_input
    valid_plots: False
    afterglow_epoch: 999999999

delete_existing_run_dir: True

do_train_template: True
do_export_template: True
verbose_validation: False

check_close:
  run_dir: ${general.run_dir}
  generated_template_approx: "/home/users/o/oleksiyu/WORK/hyperproject/transit/tests/references/gen_trXex.csv"

general:
  name: TRANSITv0v1_LHCO_test_trXex
  subfolder: TEST/
  seed: 12345 # For reproducibility
  run_dir: workspaces/${general.subfolder}${general.name}
  do_dataset_plots: False

