# Here for the documentation, for some reason dos not work with snakemake anymore
# The "last" is only updated when min_val_loss improves
# For some reason only behaves like that with snakemake jobs
# Use the custom saving callback as in default.yaml
model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${general.run_dir}/template/checkpoints
  filename: min_val_loss_{epoch:03d}
  monitor: valid/total_loss
  mode: min
  save_last: True
  auto_insert_metric_name: False

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step
