model_chekpoint_custom:
  _target_: transit.src.models.callbacks.SaveLastEveryEpoch
  dirpath: ${general.run_dir}/template/checkpoints
  filename: last.ckpt

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step