several_confs:
  oversampling_experiment:
    run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/cwola_OEnone/
    cwola_eval_path: ${general.run_dir}/plots/cwola_OEnone/
    cwola_eval_name: "oversampling_experiment"
    datasets:
      datasr: 
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/bkg200K_seed42.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "data"
            new_df_dict: {"data": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "data"
            column_name: "is_signal"
            column_values: 0
      template:
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/tem200K_seed1.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "template"
            new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "template"
            column_name: "is_signal"
            column_values: -1
      extra_signal: null
      extra_bkg: null
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0]
    extra_bkg: 0
    extra_signal: 0
  OE1:
    run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/OE1/
    cwola_eval_path: ${general.run_dir}/plots/OE1/
    cwola_eval_name: "OE1"
    datasets:
      datasr: 
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/bkg200K_seed42.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "data"
            new_df_dict: {"data": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "data"
            column_name: "is_signal"
            column_values: 0
      template:
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/tem200Kx1_seed1.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "template"
            new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "template"
            column_name: "is_signal"
            column_values: -1
      extra_signal: null
      extra_bkg: null
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0]
    extra_bkg: 0
    extra_signal: 0
  OE2:
    run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/OE2/
    cwola_eval_path: ${general.run_dir}/plots/OE2/
    cwola_eval_name: "OE2"
    datasets:
      datasr: 
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/bkg200K_seed42.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "data"
            new_df_dict: {"data": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "data"
            column_name: "is_signal"
            column_values: 0
      template:
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/tem200Kx2_seed1.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "template"
            new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "template"
            column_name: "is_signal"
            column_values: -1
      extra_signal: null
      extra_bkg: null
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0]
    extra_bkg: 0
    extra_signal: 0
  OE5:
    run_dir: ${general.run_dir}
    cwola_path: ${general.run_dir}/OE5/
    cwola_eval_path: ${general.run_dir}/plots/OE5/
    cwola_eval_name: "OE5"
    datasets:
      datasr: 
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/bkg200K_seed42.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "data"
            new_df_dict: {"data": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "data"
            column_name: "is_signal"
            column_values: 0
      template:
        _target_: transit.src.data.data.InMemoryDataFrameDict
        plotting_path: ${general.run_dir}/plots/input/cwola/template/
        list_order: ["data"]
        file_path: /home/users/o/oleksiyu/WORK/hyperproject/user/mock_data/tem200Kx5_seed1.h5
        processor_cfg: 
          - _target_: transit.src.data.data.ProcessorSplitDataFrameVars
            frame_name: "template"
            new_df_dict: {"template": ['m_j1', 'del_m', 'del_R', 'tau21_j1', "tau21_j2", "m_jj"]}
          - _target_: transit.src.data.data.ProcessorAddColumn
            frame_name: "template"
            column_name: "is_signal"
            column_values: -1
      extra_signal: null
      extra_bkg: null
    cwola_subfolders: window_3100_3300__3700_3900/dope_3000/
    mode: standard
    num_signal: 3000
    sideband_1: "3100_3300"
    sideband_2: "3700_3900"
    num_folds: 5
    max_iter: 250
    early_stopping: 1
    validation_fraction: 0.1
    class_weight: balanced
    num_ensemble: 5
    seeds: [0]
    extra_bkg: 0
    extra_signal: 0